### PR TITLE
Added GetUsersAgreements to the terms api client.

### PR DESCRIPTION
**Pull request by alesstimec**

### CODE REVIEW

**Comment by mattyw** [comment]
LGTM

**Comment by alesstimec** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Comment by mattyw** [comment]
Notyourday.gif

**Pull request merged**
