### PR TITLE
JUJU_TERMS environment variable for base terms service url.

### PR DESCRIPTION
**Pull request by alesstimec**

### CODE REVIEW

**Comment by mattyw** [comment]
Didn't we have problems with this approach? namely it's possible to change config to a terms service which doesn't support the charmstore juju is pointing to

**Comment by cmars** [comment]
@mattyw I think this would only be used for cases where juju needs to contact the terms service directly: `juju agree`, `juju list-agreements`. It would not affect cases where the charmstore is configured to require agreement to terms on a specific server -- in those cases, the bakery controls discharging.

**Comment by mattyw** [comment]
@cmars that's sort of ok, but it limits its usefulness

**Comment by cmars** [comment]
LGTM

**Comment by mattyw** [comment]
LGTM - but I wish we could configure the charmstore as well

**Comment by alesstimec** [comment]
$$merge$$

**Pull request merged**
