### PR TITLE
Use new jujuclient store for model info and refactor tests

### PR DESCRIPTION
**Pull request by wallyworld**
The old configstore is replaced by the jujuclient store.
Test are refactored to use the in memory store to avoid writes to disk.

### CODE REVIEW

**Comment by cmars** [comment]
Thanks for this! LGTM, but I'd like @tasdomas to take a look.

**Comment by tasdomas** [comment]
LGTM

**Comment by cmars** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$ now with dependencies that will pass the tests.

**Pull request merged**
