### PR TITLE
Update to macaroon/macaroon-bakery v2-unstable

### PR DESCRIPTION
**Pull request by Veebers**

### CODE REVIEW

**Comment by cmars** [comment]
!!build!!

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
(i did manage to set up a bot on this branch, hopefully the tests work)

**Comment by Veebers** [comment]
Oh, I'll push up the test fix now, wallyworld sorted it out.

**Comment by Veebers** [comment]
!!build!!

**Comment by jameinel** [comment]
I copied one of the other bot scripts, but it seems it has 2 issues:
for file in '"tests.xml"'
+ cp /var/lib/jenkins/workspace/github-check-merge-juju-romulus/build/tests.xml /var/lib/jenkins/workspace/github-check-merge-juju-romulus/
cp: cannot stat '/var/lib/jenkins/workspace/github-check-merge-juju-romulus/build/tests.xml': No such file or directory

1) why wouldn't that 'cp' fail the test suite
2) Why isn't it generating the tests.xml that it expects (presumably to integrate with Jenkins nicely)

**Comment by cmars** [comment]
@alesstimec FYI.. core is updating to macaroon-bakery.v2. We'll soon need to follow suit in omni.

**Comment by Veebers** [comment]
$$merge$$

**Comment by Veebers** [comment]
$$merge$$

**Comment by cmars** [comment]
@Veebers Thanks for setting up the buildbot on this project!

**Pull request merged**
