### PR TITLE
update gnuflag dependency

### PR DESCRIPTION
**Pull request by nskaggs**
In support of https://github.com/juju/juju/pull/5956

### CODE REVIEW

**Comment by natefinch** [comment]
LGTM once you update the deps for juju/cmd and juju/juju after they get the launchpad excision updates.

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
I've updated every depends to match juju/juju, but still showing a unit test failure. See http://juju-ci.vapour.ws:8080/job/github-merge-juju-romulus/59/console

**Comment by nskaggs** [comment]
cmars to the rescue! #60

**Pull request closed without merging**
