### PR TITLE
Rename service to application

### PR DESCRIPTION
**Pull request by wallyworld**
Service is being renamed to application. Dependencies have been updated. This change uses the new deps and replaces Service with Application where required.

### CODE REVIEW

**Comment by axw** [comment]
LGTM

**Comment by cmars** [comment]
NOT LGTM. This will break HTTP request wireformats. Juju API related changes are probably fine.

**Comment by wallyworld** [comment]
I've just landed another update which changes the URIs. I need to talk to @cmars  to see how best to roll this out.

**Comment by cmars** [comment]
@wallyworld We're not changing the HTTP API as it is not user-facing.

**Comment by cmars** [comment]
@wallyworld I think we'll add alias endpoints for the new convention some time later this cycle, deprecating the old convention, phasing it out completely by Juju 2.1. Since it's not user facing, we're not in any rush to make changes to the endpoints.

**Comment by cmars** [comment]
Landed #43 with these changes minus HTTP API changes.

**Pull request closed without merging**
